import { _electron as electron } from 'playwright'
import electronPath from 'electron'
import assert from 'node:assert/strict'
import { mkdtemp, mkdir, writeFile, rm, realpath } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
const repo = path.resolve('..')
const userData = await mkdtemp(path.join(tmpdir(), 'desktop-ui-'))
const secondProject = await realpath(await mkdtemp(path.join(tmpdir(), 'desktop-second-')))
await writeFile(path.join(secondProject, 'CLAUDE.md'), '# 第二项目\n只有第二项目可见的内容')
await writeFile(path.join(userData, 'projects.json'), JSON.stringify([{ path: repo, name: path.basename(repo) }, { path: secondProject, name: path.basename(secondProject) }]))
await mkdir('test-results', { recursive: true })
let app
try {
  app = await electron.launch({ executablePath: electronPath, args: ['.', `--user-data-dir=${userData}`] })
  const page = await app.firstWindow()
  const settle = () => page.waitForFunction(() => !document.querySelector(".view-enter-active, .view-leave-active, .results-enter-active, .results-leave-active"))
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.locator('.file-card').first().waitFor()
  const count = await page.locator('.file-card').count()
  assert.ok(count > 20, 'real repository Markdown appears')
  const anchors = () => page.evaluate(() => ['.heading-line', '.search', '.tools select'].map(selector => {
    const { x, y, width, height } = document.querySelector(selector).getBoundingClientRect()
    return { x, y, width, height }
  }))
  const alignment = []
  for (const width of [1380, 800]) {
    await app.evaluate(({ BrowserWindow }, width) => BrowserWindow.getAllWindows()[0].setSize(width, 900), width)
    await settle()
    const expected = await anchors()
    for (const name of [/^最近更新/, /^CLAUDE.md/, /^项目概览/, /^全部内容/]) {
      await page.locator('nav').getByRole('button', { name }).click()
      assert.ok(await page.locator('.results-enter-active').count(), 'category transition is active')
      await settle()
      assert.deepEqual(await anchors(), expected, 'header and controls stay aligned across categories')
    }
    await page.evaluate(() => { document.querySelector('.main').scrollTop = 400 })
    assert.deepEqual(await anchors(), expected, 'browsing chrome remains fixed while scrolling')
    await page.getByRole('button', { name: '一键初始化', exact: true }).click()
    await settle()
    assert.equal(await page.locator('.main').evaluate(el => el.scrollTop), 0)
    await page.getByRole('button', { name: '返回文件浏览' }).click()
    await settle()
    assert.equal(await page.locator('.main').evaluate(el => el.scrollTop), 400, 'initialization return restores scrolling')
    await page.evaluate(() => { document.querySelector('.main').scrollTop = 0 })
    alignment.push({ width, anchors: expected })
  }
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.locator('nav').getByRole('button', { name: /^CLAUDE.md/ }).click()
  await settle()
  assert.equal(await page.locator('nav button').first().evaluate(el => getComputedStyle(el).transitionDuration), '0s')
  await page.locator('nav').getByRole('button', { name: /^全部内容/ }).click()
  await settle()
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1380, 900))
  await page.screenshot({ path: 'test-results/workspace.png' })
  await page.locator('nav').getByRole('button', { name: /^CLAUDE.md/ }).click()
  await settle()
  assert.equal(await page.locator('.file-card').count(), 2)
  await page.locator('.file-card').first().click()
  await settle()
  await page.locator('.markdown').waitFor()
  assert.ok((await page.locator('.reader-meta').innerText()).includes('CLAUDE.md'))
  await page.getByRole('button', { name: /返回 CLAUDE.md/ }).click()
  await settle()
  assert.equal(await page.locator('.file-card').count(), 2)
  await page.getByRole('button', { name: /^全部内容/ }).click()
  await settle()
  await page.getByRole('textbox', { name: '搜索项目内容' }).fill('impossible-query-9347')
  await page.getByText('没有找到相关内容').waitFor()
  await page.getByRole('button', { name: '清除搜索', exact: true }).first().click()
  await settle()
  await page.getByLabel('文件排序').selectOption('name')
  await settle()
  await page.evaluate(() => { document.querySelector('.main').scrollTop = 450 })
  const position = await page.locator('.main').evaluate(el => el.scrollTop)
  await page.locator('.file-card').nth(4).evaluate(el => el.click())
  await settle()
  await settle()
  await page.getByRole('button', { name: '一键初始化', exact: true }).click()
  await settle()
  await page.getByRole('button', { name: '返回文件浏览' }).click()
  await settle()
  await page.locator('.markdown, .plain-content').waitFor()
  await page.getByRole('button', { name: /返回 全部内容/ }).click()
  await settle()
  assert.equal(await page.locator('.main').evaluate(el => el.scrollTop), position)
  await app.evaluate(({ dialog }, selectedPath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [selectedPath] }) }, secondProject)
  await page.getByRole('button', { name: '添加本地项目' }).click()
  await settle()
  await page.getByRole('heading', { name: '第二项目', exact: true }).waitFor()
  assert.equal(await page.locator('.file-card').count(), 1)
  await writeFile(path.join(secondProject, 'CLAUDE.md'), '# 刷新后的项目\n已更新内容')
  await page.getByRole('button', { name: '刷新项目' }).click()
  await settle()
  await page.getByRole('heading', { name: '刷新后的项目', exact: true }).waitFor()
  await writeFile(path.join(secondProject, 'unsafe.md'), '# 恶意正文\n<script>window.infected = true</script>\n<img src="https://example.org/tracking.png" onerror="window.infected = true">')
  await page.getByRole('button', { name: '刷新项目' }).click()
  await settle()
  await page.getByRole('heading', { name: '恶意正文', exact: true }).waitFor()
  await page.getByRole('button', { name: /恶意正文/ }).click()
  await settle()
  assert.equal(await page.locator('.markdown script, .markdown img').count(), 0)
  assert.equal(await page.evaluate(() => window.infected), undefined)
  await page.getByRole('button', { name: /返回 全部内容/ }).click()
  await settle()
  await page.getByLabel('切换项目').selectOption(repo)
  await settle()
  await page.locator('.file-card').nth(10).waitFor()
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(800, 720))
  await page.screenshot({ path: 'test-results/narrow.png' })
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth), false)
  const rejected = await page.evaluate(async () => { try { await window.projects.scan('/'); return false } catch { return true } })
  assert.equal(rejected, true)
  assert.deepEqual(errors, [])
  await app.close()
  app = await electron.launch({ executablePath: electronPath, args: ['.', `--user-data-dir=${userData}`] })
  const restored = await app.firstWindow()
  await restored.locator('.file-card').first().waitFor()
  assert.equal(await restored.getByLabel('切换项目').locator('option').count(), 2)
  assert.equal(await restored.getByLabel('切换项目').inputValue(), repo)
  console.log(JSON.stringify({ passed: true, repositoryFiles: count, alignment, checks: ['stable anchors at two widths', 'sticky browsing controls', 'category transition', 'reduced motion', 'initialization scroll restoration', 'real files', 'category', 'detail', 'search', 'scroll restoration', 'project switch', 'refresh', 'sanitization', 'narrow layout', 'IPC project boundary', 'renderer errors', 'directory selection', 'restart persistence'] }))
} catch (error) {
  if (app) { const page = await app.firstWindow(); await page.screenshot({ path: 'test-results/failure.png' }); console.log((await page.locator('main').innerText()).slice(0, 1000)); }
  throw error
} finally {
  if (app) await app.close()
  await rm(userData, { recursive: true, force: true }); await rm(secondProject, { recursive: true, force: true })
}
